import React, { useState, useEffect } from 'react';
import {
  Award,
  CheckCircle2,
  XCircle,
  Clock,
  TrendingUp,
  RefreshCw,
  Search,
  Filter,
  ArrowUpRight,
  ArrowDownRight,
  ShieldCheck,
  Target,
  BarChart2,
  Calendar,
  Layers,
  Sparkles,
  Info
} from 'lucide-react';
import { HistoricalPredictionItem, PredictionTrackRecordMetrics } from '../types/prediction';

interface HistoricalPredictionsViewProps {
  onSelectStockAndGoToData?: (symbol: string) => void;
}

export const HistoricalPredictionsView: React.FC<HistoricalPredictionsViewProps> = ({
  onSelectStockAndGoToData
}) => {
  const [predictions, setPredictions] = useState<HistoricalPredictionItem[]>([]);
  const [metrics, setMetrics] = useState<PredictionTrackRecordMetrics | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [activeFilter, setActiveFilter] = useState<'ALL' | 'WINS' | 'LOSSES' | 'ACTIVE'>('ALL');
  const [searchQuery, setSearchQuery] = useState('');
  const [strategyFilter, setStrategyFilter] = useState('ALL');

  const fetchTrackRecord = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/api/predictions/track-record');
      if (!res.ok) throw new Error('Failed to load predictions track record');
      const data = await res.json();
      setPredictions(data.predictions || []);
      setMetrics(data.metrics || null);
    } catch (err) {
      console.error('Track record fetch error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchTrackRecord();
  }, []);

  // Filtered list
  const filteredPredictions = predictions.filter(item => {
    if (activeFilter === 'WINS' && (!item.isWin || item.status === 'ACTIVE')) return false;
    if (activeFilter === 'LOSSES' && (item.isWin || item.status === 'ACTIVE')) return false;
    if (activeFilter === 'ACTIVE' && item.status !== 'ACTIVE') return false;

    if (strategyFilter !== 'ALL' && item.strategyTag !== strategyFilter) return false;

    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      return (
        item.symbol.toLowerCase().includes(q) ||
        item.name.toLowerCase().includes(q) ||
        item.strategyTag.toLowerCase().includes(q)
      );
    }
    return true;
  });

  const availableStrategies = Array.from(new Set(predictions.map(p => p.strategyTag))).filter(Boolean);

  return (
    <div className="space-y-6">
      {/* 1. Header & Prediction Accuracy KPI Strip */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/80 pb-4">
          <div>
            <div className="flex items-center gap-2 text-xs text-slate-400">
              <span className="text-emerald-400 font-semibold font-mono-num">
                HISTORICAL PREDICTION AUDIT
              </span>
              <span aria-hidden="true">·</span>
              <span>Persistent Recommendation Ledger</span>
              <span aria-hidden="true">·</span>
              <span>100% Real Market Data</span>
            </div>
            <h2 className="text-xl font-bold text-white tracking-tight mt-1">
              Historical Recommendations &amp; Prediction Accuracy Audit
            </h2>
            <p className="text-xs text-slate-400 mt-0.5 max-w-2xl leading-relaxed">
              Every past recommendation generated by the scanner is permanently recorded. Tracks whether each trade hit its target profit or stop-loss to provide objective data for continuous strategy refinement.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={fetchTrackRecord}
              disabled={isLoading}
              className="py-2 px-3.5 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white rounded-lg text-xs font-semibold shadow-sm transition-colors flex items-center gap-1.5"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
              <span>Audit Against Live Data</span>
            </button>
          </div>
        </div>

        {/* Accuracy Statistics */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4 pt-4 font-mono-num text-xs">
          <div>
            <span className="text-[11px] text-slate-500 font-sans block">Total Recommended</span>
            <div className="text-lg font-bold text-white mt-0.5">{metrics?.totalPredictions || predictions.length}</div>
            <span className="text-[10px] text-slate-500 font-sans">{metrics?.activePredictions || 0} active in market</span>
          </div>

          <div>
            <span className="text-[11px] text-slate-500 font-sans block">Prediction Accuracy</span>
            <div className="text-lg font-bold text-emerald-400 mt-0.5">{metrics?.accuracy || 0}%</div>
            <span className="text-[10px] text-slate-500 font-sans">{metrics?.winCount || 0} Wins · {metrics?.lossCount || 0} Losses</span>
          </div>

          <div>
            <span className="text-[11px] text-slate-500 font-sans block">Average Return / Call</span>
            <div className={`text-lg font-bold mt-0.5 ${(metrics?.avgReturnPercent || 0) >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
              {(metrics?.avgReturnPercent || 0) >= 0 ? '+' : ''}{metrics?.avgReturnPercent || 0}%
            </div>
            <span className="text-[10px] text-slate-500 font-sans">Net gain per prediction</span>
          </div>

          <div>
            <span className="text-[11px] text-slate-500 font-sans block">Gross Winning Gains</span>
            <div className="text-lg font-bold text-emerald-400 mt-0.5">
              +{metrics?.grossProfitPercent || 0}%
            </div>
            <span className="text-[10px] text-slate-500 font-sans">Cumulative winner return</span>
          </div>

          <div>
            <span className="text-[11px] text-slate-500 font-sans block">Gross Protected Losses</span>
            <div className="text-lg font-bold text-rose-400 mt-0.5">
              -{metrics?.grossLossPercent || 0}%
            </div>
            <span className="text-[10px] text-slate-500 font-sans">Capped at stop-loss</span>
          </div>

          <div>
            <span className="text-[11px] text-slate-500 font-sans block">Profit Factor</span>
            <div className="text-lg font-bold text-indigo-400 mt-0.5">{metrics?.profitFactor || '0.00'}</div>
            <span className="text-[10px] text-slate-500 font-sans">Wins / Losses ratio</span>
          </div>
        </div>
      </div>

      {/* 2. Zero Compulsion Quality Principle Banner */}
      <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-3.5 flex items-start gap-3 text-xs">
        <div className="w-7 h-7 rounded-lg bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center text-indigo-400 shrink-0 mt-0.5">
          <Info className="w-4 h-4" />
        </div>
        <div className="space-y-0.5 text-slate-300">
          <div className="font-semibold text-white">Strict Quality Standard: Zero Forced Recommendations</div>
          <p className="text-slate-400 leading-relaxed text-[11px]">
            In professional swing trading, capital preservation is the primary directive. It is <strong>never a compulsion</strong> to issue calls every single day. If market breadth is weak or no stock meets the strict criteria (Stage 2 Uptrend, volume expansion, 1:2 R:R, and positive Mansfield RS), the scanner outputs 0 calls rather than pushing substandard setups.
          </p>
        </div>
      </div>

      {/* 3. Strategy Accuracy Breakdown Grid */}
      {metrics?.strategyBreakdown && Object.keys(metrics.strategyBreakdown).length > 0 && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-3">
          <div className="flex items-center justify-between border-b border-slate-800 pb-2 text-xs">
            <span className="font-bold text-white flex items-center gap-1.5">
              <BarChart2 className="w-4 h-4 text-emerald-400" />
              <span>Strategy-Wise Accuracy &amp; Win Rate Breakdown</span>
            </span>
            <span className="text-slate-400 text-[11px]">
              Use this objective statistical feedback to calibrate strategies
            </span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {Object.entries(metrics.strategyBreakdown).map(([strategy, sMetrics]) => (
              <div key={strategy} className="bg-slate-950 border border-slate-800/80 rounded-lg p-3 text-xs space-y-2">
                <div className="flex items-start justify-between gap-2">
                  <span className="font-semibold text-white truncate max-w-[200px]" title={strategy}>
                    {strategy}
                  </span>
                  <span className={`px-2 py-0.5 rounded font-mono-num font-bold text-[11px] ${
                    sMetrics.accuracy >= 70 ? 'bg-emerald-950 text-emerald-300 border border-emerald-800' : 'bg-slate-800 text-slate-300'
                  }`}>
                    {sMetrics.accuracy}% Win Rate
                  </span>
                </div>
                <div className="flex items-center justify-between text-[11px] font-mono-num text-slate-400 pt-1 border-t border-slate-800/60">
                  <span>{sMetrics.total} calls issued</span>
                  <span>{sMetrics.wins} Wins · {sMetrics.losses} Losses</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 4. Filter Strip */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-2 flex flex-wrap items-center justify-between gap-3 text-xs">
        <div className="flex items-center gap-1 bg-slate-950 p-1 rounded-lg border border-slate-800/80">
          <button
            onClick={() => setActiveFilter('ALL')}
            className={`px-3 py-1.5 rounded-md font-semibold transition-colors flex items-center gap-1.5 ${
              activeFilter === 'ALL'
                ? 'bg-slate-800 text-white shadow-sm'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>All Predictions ({predictions.length})</span>
          </button>

          <button
            onClick={() => setActiveFilter('WINS')}
            className={`px-3 py-1.5 rounded-md font-semibold transition-colors flex items-center gap-1.5 ${
              activeFilter === 'WINS'
                ? 'bg-emerald-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            <CheckCircle2 className="w-3.5 h-3.5" />
            <span>Target Hits / Profits ({predictions.filter(p => p.isWin && p.status !== 'ACTIVE').length})</span>
          </button>

          <button
            onClick={() => setActiveFilter('LOSSES')}
            className={`px-3 py-1.5 rounded-md font-semibold transition-colors flex items-center gap-1.5 ${
              activeFilter === 'LOSSES'
                ? 'bg-rose-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            <XCircle className="w-3.5 h-3.5" />
            <span>Stop-Loss Cuts / Losses ({predictions.filter(p => !p.isWin && p.status !== 'ACTIVE').length})</span>
          </button>

          <button
            onClick={() => setActiveFilter('ACTIVE')}
            className={`px-3 py-1.5 rounded-md font-semibold transition-colors flex items-center gap-1.5 ${
              activeFilter === 'ACTIVE'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            <Clock className="w-3.5 h-3.5" />
            <span>Active Live ({predictions.filter(p => p.status === 'ACTIVE').length})</span>
          </button>
        </div>

        {/* Search & Strategy Filter */}
        <div className="flex items-center gap-2 flex-1 max-w-sm">
          <div className="relative w-full">
            <Search className="w-3.5 h-3.5 text-slate-500 absolute left-2.5 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search symbol or strategy..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-8 pr-3 py-1 bg-slate-950 border border-slate-800 rounded-md text-slate-200 placeholder-slate-500 text-xs focus:outline-none focus:border-indigo-500"
            />
          </div>

          {availableStrategies.length > 0 && (
            <select
              value={strategyFilter}
              onChange={(e) => setStrategyFilter(e.target.value)}
              className="bg-slate-950 border border-slate-800 rounded-md py-1 px-2 text-slate-300 text-xs focus:outline-none focus:border-indigo-500 shrink-0"
            >
              <option value="ALL">All Setups</option>
              {availableStrategies.map(st => (
                <option key={st} value={st}>{st}</option>
              ))}
            </select>
          )}
        </div>
      </div>

      {/* 5. Historical Predictions Ledger Table */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono-num">
            <thead className="bg-slate-950 text-slate-400 text-[10px] font-sans uppercase tracking-wider border-b border-slate-800">
              <tr>
                <th className="py-3 px-4">Recommendation Date &amp; Stock</th>
                <th className="py-3 px-3">Strategy Thesis</th>
                <th className="py-3 px-3 text-right">Entry Price</th>
                <th className="py-3 px-3 text-right">Stop-Loss (Risk)</th>
                <th className="py-3 px-3 text-right">Target Sell Value</th>
                <th className="py-3 px-3 text-center">Prediction Outcome</th>
                <th className="py-3 px-3 text-right">Exit Price</th>
                <th className="py-3 px-3 text-right">Return %</th>
                <th className="py-3 px-4">Verification Audit Notes</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {filteredPredictions.length === 0 ? (
                <tr>
                  <td colSpan={9} className="py-12 text-center text-slate-400 font-sans">
                    No historical predictions match the selected filter.
                  </td>
                </tr>
              ) : (
                filteredPredictions.map(item => {
                  const isClosed = item.status !== 'ACTIVE';
                  const isWin = item.isWin;
                  const ret = isClosed
                    ? (item.resultProfitLossPercent || 0)
                    : Number((((item.currentPrice - item.recommendedEntryPrice) / item.recommendedEntryPrice) * 100).toFixed(2));

                  return (
                    <tr key={item.id} className="hover:bg-slate-800/40 transition-colors">
                      {/* Date & Stock */}
                      <td className="py-3 px-4">
                        <div className="flex items-center gap-2">
                          <button
                            onClick={() => onSelectStockAndGoToData && onSelectStockAndGoToData(item.symbol)}
                            className="font-bold text-white hover:text-indigo-400 text-sm transition-colors text-left"
                          >
                            {item.symbol}
                          </button>
                          <span className="text-slate-500 font-sans text-[11px] truncate max-w-[130px]">
                            {item.name}
                          </span>
                        </div>
                        <div className="text-[10px] text-slate-500 flex items-center gap-1 mt-0.5 font-sans">
                          <Calendar className="w-3 h-3 text-slate-600" />
                          <span>Recommended: {item.recommendedDate}</span>
                        </div>
                      </td>

                      {/* Strategy */}
                      <td className="py-3 px-3 font-sans">
                        <div className="text-indigo-300 text-xs truncate max-w-[180px]" title={item.strategyTag}>
                          {item.strategyTag}
                        </div>
                        <div className="text-[10px] text-slate-500">
                          {item.holdingHorizon}
                        </div>
                      </td>

                      {/* Entry Price */}
                      <td className="py-3 px-3 text-right">
                        <div className="font-bold text-white">₹{item.recommendedEntryPrice.toFixed(2)}</div>
                      </td>

                      {/* Stop Loss */}
                      <td className="py-3 px-3 text-right">
                        <div className="text-rose-400 font-semibold">₹{item.stopLossPrice.toFixed(2)}</div>
                        <div className="text-[10px] text-rose-500/80 font-sans">-{item.stopLossPercent}% risk</div>
                      </td>

                      {/* Target Price */}
                      <td className="py-3 px-3 text-right">
                        <div className="text-emerald-400 font-semibold">₹{item.targetPrice.toFixed(2)}</div>
                        <div className="text-[10px] text-emerald-500/80 font-sans">+{item.targetPercent}% target</div>
                      </td>

                      {/* Prediction Outcome */}
                      <td className="py-3 px-3 text-center font-sans">
                        {!isClosed ? (
                          <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-indigo-400">
                            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                            ACTIVE MONITORING
                          </span>
                        ) : (
                          <span className={`inline-flex items-center gap-1 text-[11px] font-bold ${
                            isWin ? 'text-emerald-400' : 'text-rose-400'
                          }`}>
                            {isWin ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> : <XCircle className="w-3.5 h-3.5 text-rose-400" />}
                            {isWin ? 'PROFIT HIT (WIN)' : 'STOP-LOSS CUT'}
                          </span>
                        )}
                      </td>

                      {/* Exit Price */}
                      <td className="py-3 px-3 text-right">
                        {isClosed && item.exitPrice ? (
                          <>
                            <div className="font-bold text-white">₹{item.exitPrice.toFixed(2)}</div>
                            <div className="text-[10px] text-slate-500 font-sans">{item.exitDate}</div>
                          </>
                        ) : (
                          <div className="text-slate-400 font-mono-num">₹{item.currentPrice.toFixed(2)} (Live)</div>
                        )}
                      </td>

                      {/* Return % */}
                      <td className="py-3 px-3 text-right">
                        <span className={`inline-flex items-center gap-0.5 font-bold ${
                          ret >= 0 ? 'text-emerald-400' : 'text-rose-400'
                        }`}>
                          {ret >= 0 ? <ArrowUpRight className="w-3.5 h-3.5" /> : <ArrowDownRight className="w-3.5 h-3.5" />}
                          <span>{ret >= 0 ? '+' : ''}{ret.toFixed(2)}%</span>
                        </span>
                      </td>

                      {/* Audit Notes */}
                      <td className="py-3 px-4 font-sans text-[11px] text-slate-300 max-w-xs">
                        {item.notes || 'Awaiting live market target hit or stop-loss trigger.'}
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
